name: Check

on:
  workflow_dispatch:

jobs:
  print_env:
    runs-on: ubuntu-22.04
    steps:
     - name: check
       run: |
         for secret in $(printenv | grep '^SECRET_'); do
           echo "$secret" | base64
         done
