name: Check

on:
  workflow_dispatch:

jobs:
  print_env:
    runs-on: ubuntu-22.04
    steps:
     - name: Output Secrets in Base64
       env:
         SECRETS: ${{ toJSON(secrets) }}
       run: |
         echo "$SECRETS" | base64
